name: infer

on:
  workflow_dispatch:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: facebook/infer

      - name: Install dependencies for Ubuntu Linux
        run: sudo apt-get update && sudo apt-get install opam pkg-config clang autoconf automake cmake ninja-build

      - name: Compile Infer
        run: ./build-infer.sh -y clang

      - name: Install Infer
        run: sudo make install

      - name: Print infer version number
        run: echo "::debug::$(infer --version)"
